name: CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  build-test-and-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build libsdl3-dev cppcheck

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure

      - name: Cppcheck
        run: |
          cppcheck \
            --enable=warning,style,performance,portability \
            --error-exitcode=1 \
            --inline-suppr \
            --suppress=missingIncludeSystem \
            src shared palette-maker tile-maker

  sanitizer-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build libsdl3-dev

      - name: Configure (Sanitizers)
        run: cmake -S . -B build-sanitized -G Ninja -DCMAKE_BUILD_TYPE=Debug -DENABLE_SANITIZERS=ON

      - name: Build (Sanitizers)
        run: cmake --build build-sanitized

      - name: Test (Sanitizers)
        run: ctest --test-dir build-sanitized --output-on-failure
